import type { NextPage } from 'next'
import styled from 'styled-components'

import Head from 'next/head'
import { Layout } from "../components"

const StyledLink = styled.a`
  margin: 0 10px;
`

interface page {
  name: string;
  href: string;
}

const pages: Array<page> = [
  {
    name: '테스트페이지',
    href: 'testpage'
  },
  {
    name: 'debounce',
    href: 'debounce'
  },
  {
    name: 'super메서드 실험',
    href: 'supertest'
  },
]

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>BGT LAB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout.Main>
        <h1>
          백규태 실험실
        </h1>
        {
          pages.map((page, idx) => (
            <StyledLink href={page.href} key={`${page.href}-${idx}`}>
              {page.name}
            </StyledLink>
          ))
        }
      </Layout.Main>
    </div>
  )
}

export default Home
